name: CI-CD

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Autenticando o usuário no Docker
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
          
      - name: Construindo a imagem e enviando para o Docker Hub
        uses: docker/build-push-action@v3.1.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            jemlima/kube-news:latest
            jemlima/kube-news:${{ github.run_number }}
    
  CD:
    needs: [CI]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Kubernetes Config
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
          
      - name: Deploy da aplicação em cluster Kubernetes
        uses: Azure/k8s-deploy@v4.2
        with:
          images: jemlima/kube-news:${{ github.run_number }}
          manifests: |
            k8s/deployment.yaml
